const USER_LOADING = 'USER_LOADING'
const USER_LOADED = 'USER_LOADED'
const AUTH_FAILURE = 'AUTH_FAILURE'
const AUTH_SUCCESS = 'AUTH_SUCCESS'

export { USER_LOADED, USER_LOADING, AUTH_FAILURE, AUTH_SUCCESS }
